# config.py
# The single source of truth for all physical constants and simulation parameters
# for the FerroCellSim project.

# --- Grid & Simulation Parameters ---
GRID_SIZE = 1000         # The simulation resolution matches the physical design units.
TIME_STEP = 0.05         # Duration of a single physics update step (in seconds).
PRECISION = 'float32'    # Data type for grids ('float32' is good for GPUs).

# --- Physical Constants (based on an 18" x 18" design) ---
PHYSICAL_SIZE_M = 0.4572  # 18 inches in meters.
FLUID_VISCOSITY = 0.08    # A property of the ferrofluid (Pa·s). Tunable.
FLUID_DENSITY = 1200.0    # kg/m^3. Typical for oil-based ferrofluid.
FLUID_MAGNETIZATION = 2.0 # How strongly the fluid reacts to field gradients. Tunable.

# --- Kepler Control Grid Parameters ---
# This is the strength of the magnetic field generated by the wires.
# It's an effective value that combines current (Amps) and physical constants (mu_0).
KEPLER_FIELD_STRENGTH = 5.0 # Tunable for visual effect.
KEPLER_ASSET_FILE = 'assets/kepler_grid_topology.json'

# --- LED Array & Thermal Parameters ---
LED_BRIGHTNESS = 150  # Default brightness (0-255).
# The effect of different light colors on fluid heating (Crookes Radiometer effect).
ABSORPTION_COEFFICIENTS = {
    'red': 0.8, 'green': 0.4, 'blue': 0.2,
    'white': 0.5, 'black': 0.0
}
# The factor by which heat reduces the magnetic susceptibility of the fluid.
TEMP_SUSCEPTIBILITY_FACTOR = -0.15 # Tunable.
THERMAL_DIFFUSIVITY = 0.1     # How quickly heat spreads through the fluid.
COOLING_RATE = 0.02           # How quickly the fluid loses heat to the environment.

# --- API & Server Parameters ---
SERVER_HOST = '0.0.0.0'       # Host on all network interfaces.
SERVER_PORT = 5000            # Port for the API server.
MAX_FRAMERATE = 20            # Max updates per second to send to web clients.
